apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-semaphore
  labels:
    app: k8s-semaphore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-semaphore
  template:
    metadata:
      labels:
        app: k8s-semaphore
    spec:
      volumes:
      - name: certs
        secret:
          secretName: k8s-semaphore-certs 
      containers:
      - name: k8s-semaphore
        env:
        - name: DEBUG
          value: "true"
        - name: TLS_CERT_PATH
          value: "/etc/certs/tls.crt"
        - name: TLS_KEY_PATH
          value: "/etc/certs/tls.key"
        image: quay.io/pbertera/k8s-semaphore
        volumeMounts:
        - name:  certs
          readOnly: true
          mountPath: /etc/certs
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-semaphore
spec:
  selector:
    app: k8s-semaphore
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: "k8s-semaphore"
webhooks:
- name: "k8s-semaphore.k8-semaphore.svc"
  rules:
  - apiGroups:   [""]
    apiVersions: ["v1"]
    operations:  ["DELETE"]
    resources:   ["pods"]
    scope:       "Namespaced"
  clientConfig:
    service:
      namespace: "k8-semaphore"
      name: "k8s-semaphore"
      path: "/validate"
      port: 8080
    caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUUxVENDQTcyZ0F3SUJBZ0lVV0JZcVBrVTZtbGtBc1ZYL2czVm5YU0svK05rd0RRWUpLb1pJaHZjTkFRRUwKQlFBd2daWXhDekFKQmdOVkJBWVRBa2xVTVE0d0RBWURWUVFJREFWTVpXTmpiekVSTUE4R0ExVUVCd3dJUjJGcwpZbWxoZEdVeElEQWVCZ05WQkFvTUYwSmxjblJsY21FZ2NuVnNaWE1nZEdobElIZHZjbXhrTVJFd0R3WURWUVFMCkRBaFRaV04xY21sMGVURUxNQWtHQTFVRUF3d0NRMEV4SWpBZ0Jna3Foa2lHOXcwQkNRRVdFM05sWTNWeWFYUjUKUUdKbGNuUmxjbUV1YVhRd0hoY05NakF3TnpBeE1EY3pOekU0V2hjTk16QXdOakk1TURjek56RTRXakNCbGpFTApNQWtHQTFVRUJoTUNTVlF4RGpBTUJnTlZCQWdNQlV4bFkyTnZNUkV3RHdZRFZRUUhEQWhIWVd4aWFXRjBaVEVnCk1CNEdBMVVFQ2d3WFFtVnlkR1Z5WVNCeWRXeGxjeUIwYUdVZ2QyOXliR1F4RVRBUEJnTlZCQXNNQ0ZObFkzVnkKYVhSNU1Rc3dDUVlEVlFRRERBSkRRVEVpTUNBR0NTcUdTSWIzRFFFSkFSWVRjMlZqZFhKcGRIbEFZbVZ5ZEdWeQpZUzVwZERDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTnZYSzcyNEw0cWlkdXBDCnNET2xBVW1XYU9qUElES0xxcEJpelp0R3hGUVdxOXhnWDdMbGE4KzZHVzBORjVUalhEeW43NnU0MVRtMGhBQ1kKSkhDYzVlak8xMk8xbVZGaERDYWYwSjZBSTVrdVBpTS9sNkUxRVRzSEFvQzZsbGM5ZU5BN1pLaERPdGVLanIzeApWTk9tUXA3cml5b1Zzbnc4Z3lKZmE3dWs3bFhxbmovS1BmSUVPa3ZldlFyTzMxTzRqZFJlTjFPVnZZK0dKbHZECmxnbWF3c3BSS2szWDFUeTNKSWIwRWZ1TjVPVlpFYlYxTmVrQzd4Q1lJcEttT2RKdHR6R0VubVRVdFdndEw3WGEKOWRNQlR5RVo0RmxlVDF4QzZCYndmdTJrTHpQdzlEcmlvc0tUTnJXSHNOMjJhMXhiejZUeW4ya1gxOVQ1UXprcQpBb2w4Njg4Q0F3RUFBYU9DQVJjd2dnRVRNQjBHQTFVZERnUVdCQlNSQjNGRWEyYi9lYjJtTWhHbkduMWlrNklqCkZUQ0IxZ1lEVlIwakJJSE9NSUhMZ0JTUkIzRkVhMmIvZWIybU1oR25HbjFpazZJakZhR0JuS1NCbVRDQmxqRUwKTUFrR0ExVUVCaE1DU1ZReERqQU1CZ05WQkFnTUJVeGxZMk52TVJFd0R3WURWUVFIREFoSFlXeGlhV0YwWlRFZwpNQjRHQTFVRUNnd1hRbVZ5ZEdWeVlTQnlkV3hsY3lCMGFHVWdkMjl5YkdReEVUQVBCZ05WQkFzTUNGTmxZM1Z5CmFYUjVNUXN3Q1FZRFZRUUREQUpEUVRFaU1DQUdDU3FHU0liM0RRRUpBUllUYzJWamRYSnBkSGxBWW1WeWRHVnkKWVM1cGRJSVVXQllxUGtVNm1sa0FzVlgvZzNWblhTSy8rTmt3REFZRFZSMFRCQVV3QXdFQi96QUxCZ05WSFE4RQpCQU1DQVFZd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFKYmdBcm8raGJWUjlCMGpJWlFJc2lxakdqUE83b1BLCkJKTEducDNvNnZCZHFCL3pIYlVUM2pvOW02L2xxNEk3N1hUblJnbUhNMWs5eCtneGFZMzBNU2h4T1J4RGVBYXcKMUFjcmduWFBRMkV3djIvWXZNMVptVlc3YlVXcEg4aEhPN0pkSThVSTFZNENFYStVY2drNElSZWo4ZHo0UHBpQgpLcDBJbUtsR0ErVHZVdWYzN2xLQlc1NDJpZGRneGMzU3FhbFlUekNkT0NlbjlTV09oaUFpVndMeGpUU1MxSGExCnZVeEhwSEFYNEttb3d4b1FQYUZuVHU4Ty9uWmR6Z1kvclNLNWgxY2h6SzVNWTFnbHBzR3UyVlpnM1Y4T0ZuOW8Kei9tcWU0L1kxMTZvS00xT3d6ai81NWNGV29KbVBudmxrWTBqSWZEQTF5U2UyMFN4N0RNT1orOD0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo="
  admissionReviewVersions: ["v1", "v1beta1"]
  sideEffects: None
  timeoutSeconds: 5
